name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup build submodule
      run: mkdir lib/bin
    
    - name: Build & setup library
      run: ./setup.bat
      shell: cmd

    - name: Build .sln project
      run: msbuild Engine.sln /p:Configuration=Release
